name: Trigger auto deployment for containerapp mcserver

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mcserver-AutoDeployTrigger-64a0d593-ccdd-45e2-bd99-6ccafe03a95d.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: miencraft.azurecr.io
          username: ${{ secrets.MCSERVER_REGISTRY_USERNAME }}
          password: ${{ secrets.MCSERVER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: miencraft.azurecr.io/mcserver:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MCSERVER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            echo "Installing containerapp extension"
            az config set extension.use_dynamic_install=yes_without_prompt
            echo "Starting Deploying"
            az containerapp registry set -n mcserver -g minecraft --server miencraft.azurecr.io --username  ${{ secrets.MCSERVER_REGISTRY_USERNAME }} --password ${{ secrets.MCSERVER_REGISTRY_PASSWORD }}
            az containerapp update -n mcserver -g minecraft --image miencraft.azurecr.io/mcserver:${{ github.sha }}
